import { dateSchema, idSchema, numberSchema } from 'src/utils/schemas';
import { z } from 'zod/v4';

export const weekSchema = z.object({
  date: dateSchema,
});

export const editSchema = z.object({
  id: idSchema,
  '0code0': z.string().nullish(),
  '0goal0': numberSchema.nullish(),
  '0produced0': numberSchema.nullish(),
  '0code1': z.string().nullish(),
  '0goal1': numberSchema.nullish(),
  '0produced1': numberSchema.nullish(),
  '0code2': z.string().nullish(),
  '0goal2': numberSchema.nullish(),
  '0produced2': numberSchema.nullish(),
  '0comment': z.string().nullish(),
  '1code0': z.string().nullish(),
  '1goal0': numberSchema.nullish(),
  '1produced0': numberSchema.nullish(),
  '1code1': z.string().nullish(),
  '1goal1': numberSchema.nullish(),
  '1produced1': numberSchema.nullish(),
  '1code2': z.string().nullish(),
  '1goal2': numberSchema.nullish(),
  '1produced2': numberSchema.nullish(),
  '2code0': z.string().nullish(),
  '2goal0': numberSchema.nullish(),
  '2produced0': numberSchema.nullish(),
  '2code1': z.string().nullish(),
  '2goal1': numberSchema.nullish(),
  '2produced1': numberSchema.nullish(),
  '2code2': z.string().nullish(),
  '2goal2': numberSchema.nullish(),
  '2produced2': numberSchema.nullish(),
  '3code0': z.string().nullish(),
  '3goal0': numberSchema.nullish(),
  '3produced0': numberSchema.nullish(),
  '3code1': z.string().nullish(),
  '3goal1': numberSchema.nullish(),
  '3produced1': numberSchema.nullish(),
  '3code2': z.string().nullish(),
  '3goal2': numberSchema.nullish(),
  '3produced2': numberSchema.nullish(),
  '4code0': z.string().nullish(),
  '4goal0': numberSchema.nullish(),
  '4produced0': numberSchema.nullish(),
  '4code1': z.string().nullish(),
  '4goal1': numberSchema.nullish(),
  '4produced1': numberSchema.nullish(),
  '4code2': z.string().nullish(),
  '4goal2': numberSchema.nullish(),
  '4produced2': numberSchema.nullish(),
  assistanceId: z.string().nullish(),
  '1comment': z.string().nullish(),
  '2comment': z.string().nullish(),
  '3comment': z.string().nullish(),
  '4comment': z.string().nullish(),
  name: z.string().nullish(),
  noEmpleado: z.string().nullish(),
  areaId: z.string().nullish(),
  positionId: z.string().nullish(),
  incidenceId0: z.string().nullish(),
  incidenceId1: z.string().nullish(),
  incidenceId2: z.string().nullish(),
  incidenceId3: z.string().nullish(),
  incidenceId4: z.string().nullish(),
  '0average': z.string().nullish(),
  '1average': z.string().nullish(),
  '2average': z.string().nullish(),
  '3average': z.string().nullish(),
  '4average': z.string().nullish(),
});
